//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSIONFORMDETAIL
    {
        public int ID { get; set; }
        public byte[] PHOTOID { get; set; }
        public string PHOTOIDTYPE { get; set; }
        public string ENROLMENTNO { get; set; }
        public string CENTERCODE { get; set; }
        public string STUDENTNAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public string COURSECODE { get; set; }
        public string ACCADEMYNAME { get; set; }
        public string FATHERNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public string NATIONALITY { get; set; }
        public string ADDRESSES { get; set; }
        public string MOBILENO { get; set; }
        public string NAMEOFSTUDYCENTER { get; set; }
        public string CREATEDDTM { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
