//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VasmmEntities : DbContext
    {
        public VasmmEntities()
            : base("name=VasmmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMISSIONFORMDETAIL> ADMISSIONFORMDETAILS { get; set; }
        public virtual DbSet<COURSEMASTER> COURSEMASTERs { get; set; }
        public virtual DbSet<FACULITYDETAIL> FACULITYDETAILs { get; set; }
        public virtual DbSet<LATESTNEW> LATESTNEWS { get; set; }
        public virtual DbSet<STUDENTSENQUIRY> STUDENTSENQUIRies { get; set; }
        public virtual DbSet<VASMUSER> VASMUSERs { get; set; }
        public virtual DbSet<RollMaster> RollMasters { get; set; }
    }
}
