//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FACULITYDETAIL
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Surname { get; set; }
        public string TownCity { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Postcode { get; set; }
        [Display(Name ="type")]
        public string FACULTYTYPE { get; set; }
        public Nullable<long> HomeTel { get; set; }
        public Nullable<long> MobTel { get; set; }
        public string EMAILID { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<double> PAYSCALE { get; set; }
        public Nullable<System.DateTime> APPOINTMENTDATE { get; set; }
        public string QUALIFICATION { get; set; }
        public byte[] PHOTOID { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> CREATEDDTM { get; set; }
    }
}
