//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LATESTNEW
    {
        public int ID { get; set; }
        [DataType(DataType.Text)]
        public string TITLE { get; set; }
        [Display(Name ="new")]
        [DataType(DataType.MultilineText)]
        public string NEWSDETAILS { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> CREATEDDTM { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
