//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTSENQUIRY
    {
        public int ID { get; set; }
        public string STUDENTNAME { get; set; }
        public string COURSENAME { get; set; }
        public string STUDENTEMAIL { get; set; }
        public string PHONE { get; set; }
        public string QUERY { get; set; }
        public Nullable<System.DateTime> CREATEDDTM { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
